Increase Newton.Json version to fix the build error in VS2019: (#231)
Severity Code Line Description File Project Category Suppression State Tool
Error CS1705 1 Assembly 'Microsoft.Psi.Data' with identity 'Microsoft.Psi.Data, Version=0.17.52.1, Culture=neutral, PublicKeyToken=null' uses 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' C:\fork\psi\Sources\Visualization\Microsoft.Psi.Visualization.Windows\CSC Microsoft.Psi.Visualization.Windows Build N/A Compiler